### ISSUE TITLE
Tables without glass are set as opaque, causing improper culling with MoreCulling mod

### ISSUE THREAD

**Issue by SplendidAlakey** [jexline/exline-furniture#19]
**MC** 1.18.2
**[MoreCulling](https://github.com/fxmorin/MoreCulling)** 0.1.4-alpha
**Exline's Furniture** 2.1.0

![2022-06-09_16 29 29](https://user-images.githubusercontent.com/86702831/172872784-2092f701-8c34-4908-a585-5d50bdd8ec71.png)
![2022-06-09_16 29 56](https://user-images.githubusercontent.com/86702831/172872796-7dd001de-6aab-4c21-ae7c-8ba0a5ccd16e.png)

Logs: https://gist.github.com/Footage2-Amply-Pounce/83161f04055ca503d54c6a1b30d1cb28

Initially reported to MoreCulling: https://github.com/fxmorin/MoreCulling/issues/16, but the dev [replied](https://github.com/fxmorin/MoreCulling/issues/16#issuecomment-1151340686) that it's something that should be done on EF's side.

**Comment by jexline** [comment]
I have it as nonOpaque, but believe the problem is that im using it as a regular block. i changed the voxel shape for the table so now it will be the top and legs for the bounding box. let me know if this fixed your problem :) https://www.curseforge.com/minecraft/mc-mods/exlines-furniture/files/3824945
also did the same for 1.19 for when or if you need it on that one too

**Comment by SplendidAlakey** [comment]
Yep, thank you for a swift fix!

And yes, I am going to update to 1.19 once all my mods are updated, so thanks again.
